services:
  - type: web
    name: parrainage-app
    env: php
    buildCommand: composer install --no-interaction --prefer-dist --optimize-autoloader && npm install && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: Parrainage App
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          name: parrainage-app
          type: web
          property: host
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: parrainage-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: parrainage-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: parrainage-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: parrainage-db
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: parrainage-db
          property: password

databases:
  - name: parrainage-db
    databaseName: parrainage
    plan: free
